impl: test sub cmd with support for --manifest-path (#280)
paritytech/cargo-contract pull request #283
Opened 2021-05-27 06:54 UTC by chiefbiiko

drafts `cargo contract test [FLAGS] [--manifest-path]`

in this first impl stdout is uncolored

let me know if you care much for the colors

2021-06-17 12:16 UTC, Robbepop reviewed
What precisely is the win of having `cargo contract test` over just using `cargo test` as it can be done right now?

2021-06-17 12:22 UTC, cmichi commented
@Robbepop At the moment `cargo contract --help` shows the sub-command as:
```
test     Test the smart contract off-chain
```
If one invokes `cargo contract test` currently this results in an `unimplemented!` panic though, which is why people were irritated and started creating issues about it in this repository.

So we could either remove the sub-command or just hand over to `cargo test`. After talking to @ascjones we concluded that it's probably best to just spawn a sub-process with `cargo test` until we have further ideas what to do with the sub-command. 

What's your opinion?

2021-06-17 12:33 UTC, Robbepop commented
> @Robbepop At the moment `cargo contract --help` shows the sub-command as:
> 
> ```
> test     Test the smart contract off-chain
> ```
> 
> If one invokes `cargo contract test` currently this results in an `unimplemented!` panic though, which is why people were irritated and started creating issues about it in this repository.
> 
> So we could either remove the sub-command or just hand over to `cargo test`. After talking to @ascjones we concluded that it's probably best to just spawn a sub-process with `cargo test` until we have further ideas what to do with the sub-command (#280).
> 
> What's your opinion?

I currently do not see a major reason but it might help against confusion. So yeah let's do it the proposed way.

2021-06-17 13:03 UTC, cmichi requested changes
Thanks for the PR, it looks good!

I've got just some minor things. We use the writing `off-chain` everywhere, hence the suggestion of keeping it consistent.

2021-06-17 13:03 UTC, cmichi commented on src/cmd/test.rs
> +            assert!(res.stdout.len() > 0);
Could you add another assertions which checks for something like `test result: ok. 2 passed; 0 failed; 0 ignored`?

This way we can then be sure that there was no other unrelated failure the cause of `stdout.len() > 0`.

2021-06-17 13:03 UTC, cmichi commented on CHANGELOG.md
> +- Convenient offchain testing through `cargo contract test`
```suggestion
- Convenient off-chain testing through `cargo contract test`
```

2021-06-21 15:35 UTC, chiefbiiko commented
thanks for the review
i have included your suggestions now

2021-07-03 16:03 UTC, cmichi approved these changes
Thanks for the PR!

2021-07-03 16:04 UTC, merged