Change default opitmization pass to focus on code size
paritytech/cargo-contract pull request #305
Opened 2021-07-19 20:49 UTC by HCastano

This PR changes the default optimization option passed to `wasm-opt` from `-O3` to `-Os`.
This saves us around 0.2-0.3K according to [these rough benchmarks](https://github.com/paritytech/cargo-contract/issues/110#issuecomment-882844120).

The default wasn't set to `-Oz` as I saw no noticeable size improvements, and it just
takes more time to run. However, you could also argue that since contracts are in general
quite small the extra time for `-Oz` is negligible so we should enable it anyways. 

While I could be convinced of this, I'm not sure what hardware other people build on, and
the negative impact the change to `-Oz` could have for them.

2021-07-20 08:33 UTC, athei commented
We should invest everything in making contracts as small as possible. Any contract above 50KB wouldn't be viable to run on a parachain anyways. So the optimization time should be negligible.

2021-07-20 21:13 UTC, athei approved these changes

2021-07-21 05:59 UTC, cmichi requested changes
Thank you!

Could you add a `### Changed` subsection to the `Unreleased` section of our `CHANGELOG.md`: https://github.com/paritytech/cargo-contract/blob/master/CHANGELOG.md ?

2021-07-21 19:04 UTC, HCastano commented
> Thank you!
> 
> Could you add a `### Changed` subsection to the `Unreleased` section of our `CHANGELOG.md`: https://github.com/paritytech/cargo-contract/blob/master/CHANGELOG.md ?

I like that a `CHANGELOG` is kept. However, there's gotta be a way to automate this, no? Maybe @s3krit can share some of his automation secrets 👀

2021-07-22 03:32 UTC, cmichi approved these changes

2021-07-22 03:32 UTC, merged